#!/bin/bash

#example for logging 
<<comment


In shell scripting, the logger command is used to send messages to the system logger (syslog). By default, the logs generated by logger are written to the system log file, which is typically located at /var/log/syslog or /var/log/messages, depending on the operating system.

Here's a breakdown of where the logs might go:

Ubuntu/Debian-based systems: Logs are usually written to /var/log/syslog.
Red Hat/CentOS-based systems: Logs are usually written to /var/log/messages.


comment


logger "This is from ${0}"